import 'package:get/get.dart';

class LocalizationService extends Translations {
  static getLocalizedKey(String key) {
    String currentLanguageCode = Get.locale!.languageCode;
    print('Localized key is: ${key}_$currentLanguageCode');
    return '${key}_$currentLanguageCode';
  }

  @override
  Map<String, Map<String, String>> get keys {
    const Map<String, String> lang_en = {
      "hello": "Hello world!",
      "welcome": "Welcome",
      'business_rating': "Business Ratings",
      "change_lang_msg": "Do you really want to change language?",
      "are_you_sure": "Are You Sure!",
      "email": "Email",
      "enter-your-email": "Enter your email",
      "in-valid-email": "In Valid Email",
      "password": "Password",
      "enter-your-password": "Enter your password",
      "please-enter-password": "Please Enter Password",
      "greater-then-6": "Password should be greater then 6 charactor",
      "remember-me": "Remember me",
      "forgot-assword?": "Forgot Password?",
      "link-send-successfully": "Link Send Succesfully",
      "link-send": "The Password link sent! Check your email",
      "send-request'": "Send Request'",
      "reset-password": "Reset Password",
      "username": "User Name",
      "enter-your-user-name": "Enter your user name",
      "enter-your-name": "Enter Your Name",
      "phone-number": "Phone Number",
      "enter-your-number": "Enter your number",
      "confirm-password": "Confirm Password",
      "password-dont-match": "Password does not match",
      "password-match": "Password Match",
      "log-in": "LOG IN",
      "sign-up": "SIGN UP",
      "create-new-shop": "Create new shop",
      "back": "Back",
      "shop-name": "Shop Name",
      "enter-shop-name": "Enter your shop name",
      "location": "Location",
      "enter-your-location": "Enter your location",
      "categories": "Categories",
      "fashion": "Fashion",
      "clinics": "Clinics",
      "barber-shops": "Barber shops",
      "description": "Description",
      "enter-description": "Enter Description",
      "enter-shops-description": "Enter Shops Description",
      "change-language": "Change Language",
      "to-dark": "Change to Dark Theme",
      "analysis-report": "Analysis Report",
      "users-list": "Users List",
      "account-information": "Account Information",
      "settings": "Settings",
      "introduction": "Introduction",
      "terms-policies": "Terms & Policies",
      "log-out": "LogOut",
      "save-changes": "Save Changes",
      "edit": "Edit",
      "search_businesses": "Search Businesses",
      "shop_not_found": "Shop not found",
      "fahion-shop": "Fahion Shop",
      "barber-shop": "Barber Shop",
      "see-all": "SEE ALL",
      "display-options": "Display Options",
      "personal-information": "Personal Information",
      "phone": "Phone",
      "notification-settings": "Notification Settings",
      "not-display": "Not display",
      "get-notifications": "Get notifications",
      "hide-account": "Hide Account",
      "exit-application": "Exit the Application",
      "delete-account": "Delete Data and Account",
      "write-review": "Write a review",
      "reviews-user": "Reviews by user",
      "save-image": "Save Image",
      "change-image": "Change Image",
      "number": "Number",
      "jan": "January",
      "feb": "February",
      "mar": "March",
      "apr": "April",
      "may": "May",
      "jun": "June",
      "jul": "July",
      "aug": "August",
      "sep": "September",
      "oct": "October",
      "nov": "November",
      "dec": "December",
      "total-user": "Total User",
      "average-ratings": "Average Ratings",
      "no-shops": "No shops created yet",
      "submit": "Submit",
      "feedback": "Feedback",
      "q1":
          "How likely are you to recommend (our product or service) to others?",
      "q2": "Rate your satisfaction with our team in resolving your issue.",
      "q3": "Rate your satisfaction with our management team.",
      "q4": "Did you feel that our team answered your inquiry promptly?",
      "q5": "How likely are you to return to our organization?",
      "q6": "How satisfied were you with your experience today?",
      "q7": "Why did you choose our product/ Organization over a competitor's?",
      "q7p1": "Prince",
      "q7p2": "Quality",
      "q7p3": "Value",
      "q7p4": "Location",
      "error": "Error",
      "no": "No",
      "yes": "Yes",
      "ratings": "Ratings",
      "update_shop": "Update Shop"
    };

    const Map<String, String> lang_am = {
      "update_shop": "ሱቅ አዘምን",
      "hello": "!مرحبا بالعالم",
      "welcome": "እንኳንደህናመጣህ",
      'business_rating': "የንግድግምገማ",
      "change_lang_msg": "ቋንቋመቀየርበእርግጥ ይፈልጋሉ?",
      "are_you_sure": "እርግጠኛነህ!",
      "email": "ኢሜይል",
      "enter-your-email": "የእርስዎንኢሜይልያስገቡ",
      "in-valid-email": "የማይሰራኢሜይል",
      "password": "የይለፍቃል",
      "enter-your-password": "የይለፍቃልዎንያስገቡ",
      "please-enter-password": "የይለፍቃልዎንያስገቡ",
      "greater-then-6": "የይለፍቃሉከስድስትቁምፊዎችበላይመሆንአለበት",
      "remember-me": "አስታወስከኝ",
      "forgot-assword?": "መክፈቻቁልፉንረሳኽው?",
      "link-send-successfully": "መገናኛው በስኬትተልኳል",
      "link-send": "የይለፍቃሉመገናኛተልኳል!ኢሜሎዋንያረጋግጡ",
      "send-request": "ጥያቄዋን-ያስተላልፋ",
      "reset-password": "በድጋሚ የይለፍቃሎዎንያስገቡ",
      "username": "የተጠቃሚ ስም",
      "enter-your-user-name": "የተጠቃሚ ስም ያስገቡ",
      "enter-your-name": "ስምዋንያስገቡ",
      "phone-number": "ስምዋንያስገቡ",
      "enter-your-number": "ቁጥሮዋንያስገቡ",
      "confirm-password": "የይለፍቃልዋንያስገቡ",
      "password-dont-match": "የይለፍቃሉአልተስማማም",
      "password-match": "የይለፍቃሉተስማምተዋል",
      "log-in": "ይሙሉ/ይመዝገቡ",
      "sign-up": "በስተመጨረሻይክፈቱ/ይከፈቱ",
      "create-new-shop": "አዲስየድህረገፅግብይትይፋጠሩ",
      "back": "ይመለሱ",
      "shop-name": "የገበያው ስም",
      "enter-shop-name": "ወደገበያው ስም ይግቡ",
      "Location": "አቅጣጫ /አድራሻ",
      "enter-your-location": "አቅጣጫ /አድራሻ",
      "categories": "ዘርፎች",
      "fashion": "ፍሽን",
      "clinics": "ክሊኒኮች",
      "barber-shops": "የፀጉርቤቶች",
      "description": "መግለጫ",
      "enter-description": "ወደመግለጫ ይግቡ",
      "enter-shops-description": "የገበያዎችንመግለጫይግቡ",
      "change-language": "ቋንቋመቀየር",
      "to-dark": "ወደጠቆርያለገፅታይቀይሩ",
      "analysis-report": "የግምገማ ሪፓርት",
      "users-list": "የተጠቃሚዋችዝርዝር",
      "account-information": "የመለያመረጃ",
      "settings": "ቅንብርዝርዝር",
      "introduction": "መግቢያ/መግለጫ",
      "terms-policies": "ቃልእናፓሊሲዎች",
      "log-out": "ይውጡ /መውጣት",
      "save-changes": "ለውጦችይኑሩ/ያቆዩ",
      "edit": "አርትዕ/ማስተካከል/ማቀናበር",
      "search_businesses": "የንግድተቋማትንመፈለግ",
      "shop_not_found": "ገበያው አልተገኘም",
      "fahion-shop": "የፋሽንገበያ",
      "barber-shop": "የፀጉርቤት",
      "see-all": "ሁሉንይመልከቱ/ሁሉንማየት/መመልከት",
      "display-options": "አማራጮችንማሳየት",
      "personal-information": "የግልመረጃ/ግላዊመረጃ",
      "phone": "ስልክ",
      "notification-settings": "የማሳወቂያዝርዝርቅንብር",
      "not-display": "አለማሳየት",
      "get-notifications": "ማስታወቂያማግኘት/ይግኙ",
      "hide-account": "መለያመደበቅ",
      "exit-application": "ከመተግበርያው መውጣት",
      "delete-account": "መለያመሰረዝ",
      "write-review": "ግምገማ /መደምደሚያ",
      "reviews-user": "ተጠቃሚንበድጋሚ ማየት/መገምገም",
      "save-image": "ምስልማኖር/ያኑሩ",
      "change-image": "ምስልመቀየር/ይቀይሩ",
      "number": "ቁጥር(የመለያ/የስልክ)",
      "jan": "ጥር",
      "feb": "የካቲት",
      "mar": "መጋቢት",
      "apr": "ሚያዝያ",
      "may": "ግንቦት",
      "jun": "ሰኔ",
      "jul": "ሐምሌ",
      "aug": "ነሐሴ",
      "sep": "መስከረም",
      "oct": "ጥቅምት",
      "nov": "ጥቅምት",
      "dec": "ታህሳስ",
      "total-user": "ጠቅላላተጠቃሚ /ጥቅልተጠቃሚ",
      "average-ratings": "አማካኝደረጃ",
      "no-shops": "ምንም አይነትገበያዎችአልተፈጠሩም",
      "submit": "ማስገባት/ያስገቡ",
      "feedback": "ግብረምላሽ",
      "q1": "ምርታችንንወይም አገልግሎታችንንለሌሎችበምንደረጃ/ሁኔታ/ዝንባሌ ይጠቁማሉ/ይገልፃሉ",
      "q2": "ያሉዋትንጉዳይ/ችግርበመፍታትደረጃለቲማችንያሉዋትንእርካታደረጃያውጡለት",
      "q3": "በአስተዳደርቲማችንላይያልዎትንእርካታደረጃያውጡለት",
      "q4": "ይልዎትመሰረታዊጥያቄዎች/ፍላጓቶችበቲማችንመመለሱንይሰማዎታል",
      "q5": "ወደድርጅታችንየመመለስዝንባሌምንያህልነው",
      "q6": "ዛሬባገኙትልምድምንያህልእርካታአግኝተዋል",
      "q7": "ከሌሎችተወዳዳሪዎች በተሻለድርጅትወይንም ምርትለምንመረጡ",
      "q7p1": "Prince",
      "q7p2": "Quality",
      "q7p3": "Value",
      "q7p4": "Location",
      "error": "Error",
      "no": "No",
      "yes": "Yes",
      "ratings": "Ratings",
    };

    return {
      'en': lang_en,
      'am': lang_am,
    };
  }
}